// Package fakes provides test doubles for every interface in
// [github.com/wailorman/wwtr/internal/di]. They are intentionally hand-rolled
// (not generated by mockery/etc.) so each fake's behaviour is obvious from a
// single small file.
//
// Naming convention: a fake for di.X is named FakeX. Each fake is safe for
// single-goroutine test use; concurrent access must be synchronised by the
// caller.
package fakes

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/wailorman/wwtr/internal/di"
)

// ErrFake is the sentinel returned by fakes when asked for something they
// have been told doesn't exist. Distinct from a generic os.ErrNotExist so
// tests can assert exactly.
var ErrFake = errors.New("fakes: not set")

// ---------------------------------------------------------------------------
// FakeFS — an in-memory filesystem backed by two maps (files and symlinks).
// ---------------------------------------------------------------------------

type fsEntry struct {
	mode os.FileMode
	data []byte
}

// FakeFS is a fully in-memory FS. Symlinks are recorded separately from
// regular files so tests can distinguish Lstat behaviour. MkdirAll records
// implicit directory existence via the leading-slash convention: a path is
// considered a directory if it ends in "/" or has been the parent of any file.
type FakeFS struct {
	mu       sync.Mutex
	files    map[string]fsEntry
	symlinks map[string]string // link -> target
	dirs     map[string]struct{}
	errors   map[string]error // path -> error to return on next op
}

func NewFakeFS() *FakeFS {
	return &FakeFS{
		files:    map[string]fsEntry{},
		symlinks: map[string]string{},
		dirs:     map[string]struct{}{"/": {}, ".": {}},
		errors:   map[string]error{},
	}
}

// InjectError forces the next op on path to return err. Use to test
// permission/IO-error code paths.
func (f *FakeFS) InjectError(path string, err error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	f.errors[path] = err
}

func (f *FakeFS) consumeError(path string) error {
	if err, ok := f.errors[path]; ok {
		delete(f.errors, path)
		return err
	}
	return nil
}

func (f *FakeFS) ReadFile(path string) ([]byte, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return nil, err
	}
	if e, ok := f.files[path]; ok {
		return append([]byte(nil), e.data...), nil
	}
	if _, ok := f.symlinks[path]; ok {
		target := f.symlinks[path]
		if e, ok := f.files[target]; ok {
			return append([]byte(nil), e.data...), nil
		}
	}
	return nil, os.ErrNotExist
}

func (f *FakeFS) WriteFile(path string, data []byte, perm os.FileMode) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return err
	}
	f.markParents(path)
	f.files[path] = fsEntry{mode: perm, data: append([]byte(nil), data...)}
	delete(f.symlinks, path)
	return nil
}

func (f *FakeFS) Stat(path string) (os.FileInfo, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return nil, err
	}
	if e, ok := f.files[path]; ok {
		return fakeFileInfo{name: base(path), size: int64(len(e.data)), mode: e.mode, isDir: false}, nil
	}
	if target, ok := f.symlinks[path]; ok {
		// Stat follows the link.
		if e, ok := f.files[target]; ok {
			return fakeFileInfo{name: base(path), size: int64(len(e.data)), mode: e.mode}, nil
		}
		if _, ok := f.dirs[target]; ok {
			return fakeFileInfo{name: base(path), mode: os.ModeDir | 0o755, isDir: true}, nil
		}
	}
	if _, ok := f.dirs[path]; ok {
		return fakeFileInfo{name: base(path), mode: os.ModeDir | 0o755, isDir: true}, nil
	}
	return nil, os.ErrNotExist
}

func (f *FakeFS) Lstat(path string) (os.FileInfo, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return nil, err
	}
	if _, ok := f.symlinks[path]; ok {
		return fakeFileInfo{name: base(path), mode: os.ModeSymlink | 0o777}, nil
	}
	// Inline the Stat logic without re-acquiring the mutex (Stat is a separate
	// public method that locks on its own; calling it here would deadlock).
	if e, ok := f.files[path]; ok {
		return fakeFileInfo{name: base(path), size: int64(len(e.data)), mode: e.mode, isDir: false}, nil
	}
	if _, ok := f.dirs[path]; ok {
		return fakeFileInfo{name: base(path), mode: os.ModeDir | 0o755, isDir: true}, nil
	}
	return nil, os.ErrNotExist
}

func (f *FakeFS) MkdirAll(path string, perm os.FileMode) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return err
	}
	f.dirs[path] = struct{}{}
	return nil
}

func (f *FakeFS) Remove(path string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return err
	}
	if _, ok := f.files[path]; ok {
		delete(f.files, path)
		return nil
	}
	if _, ok := f.symlinks[path]; ok {
		delete(f.symlinks, path)
		return nil
	}
	return os.ErrNotExist
}

func (f *FakeFS) RemoveAll(path string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(path); err != nil {
		return err
	}
	for p := range f.files {
		if strings.HasPrefix(p, path) {
			delete(f.files, p)
		}
	}
	for p := range f.symlinks {
		if strings.HasPrefix(p, path) {
			delete(f.symlinks, p)
		}
	}
	for d := range f.dirs {
		if strings.HasPrefix(d, path) {
			delete(f.dirs, d)
		}
	}
	return nil
}

func (f *FakeFS) Symlink(target, link string) error {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(link); err != nil {
		return err
	}
	f.markParents(link)
	f.symlinks[link] = target
	delete(f.files, link)
	return nil
}

func (f *FakeFS) Readlink(link string) (string, error) {
	f.mu.Lock()
	defer f.mu.Unlock()
	if err := f.consumeError(link); err != nil {
		return "", err
	}
	if target, ok := f.symlinks[link]; ok {
		return target, nil
	}
	return "", os.ErrNotExist
}

func (f *FakeFS) Exists(path string) bool {
	_, err := f.Stat(path)
	return err == nil
}

func (f *FakeFS) markParents(path string) {
	d := dir(path)
	for d != "" && d != "/" && d != "." {
		f.dirs[d] = struct{}{}
		d = dir(d)
	}
}

// Snapshot returns a sorted list of all paths (files, symlinks, dirs) for
// deterministic assertions in tests.
func (f *FakeFS) Snapshot() []string {
	f.mu.Lock()
	defer f.mu.Unlock()
	out := []string{}
	for p := range f.files {
		out = append(out, "F:"+p)
	}
	for p := range f.symlinks {
		out = append(out, "L:"+p)
	}
	for p := range f.dirs {
		out = append(out, "D:"+p)
	}
	sort.Strings(out)
	return out
}

func base(p string) string {
	i := strings.LastIndex(p, "/")
	if i < 0 {
		return p
	}
	return p[i+1:]
}

func dir(p string) string {
	i := strings.LastIndex(p, "/")
	if i < 0 {
		return ""
	}
	if i == 0 {
		return "/"
	}
	return p[:i]
}

type fakeFileInfo struct {
	name  string
	size  int64
	mode  os.FileMode
	isDir bool
}

func (f fakeFileInfo) Name() string       { return f.name }
func (f fakeFileInfo) Size() int64        { return f.size }
func (f fakeFileInfo) Mode() os.FileMode  { return f.mode }
func (f fakeFileInfo) ModTime() time.Time { return time.Time{} }
func (f fakeFileInfo) IsDir() bool        { return f.isDir }
func (f fakeFileInfo) Sys() any           { return nil }

// ---------------------------------------------------------------------------
// RecordShell — captures every command, returns canned results.
// ---------------------------------------------------------------------------

// ShellResult is what a single Run call returns.
type ShellResult struct {
	Stdout   []byte
	Stderr   []byte
	ExitCode int
	Err      error
}

// RecordShell is a ShellRunner that records every invocation and returns
// caller-programmed results. The programming model is FIFO: each Run call
// consumes the next element of Results. If Results is exhausted, Run returns
// an error (a test bug).
type RecordShell struct {
	mu      sync.Mutex
	Calls   []string
	Results []ShellResult
}

func (r *RecordShell) Run(_ context.Context, cmd string) ([]byte, []byte, int, error) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.Calls = append(r.Calls, cmd)
	if len(r.Results) == 0 {
		return nil, nil, -1, fmt.Errorf("RecordShell: no programmed result for %q", cmd)
	}
	res := r.Results[0]
	r.Results = r.Results[1:]
	return res.Stdout, res.Stderr, res.ExitCode, res.Err
}

// Program appends a result to be returned by the next Run call(s).
func (r *RecordShell) Program(res ...ShellResult) {
	r.mu.Lock()
	defer r.mu.Unlock()
	r.Results = append(r.Results, res...)
}

// ---------------------------------------------------------------------------
// FakeGit — returns canned paths.
// ---------------------------------------------------------------------------

type FakeGit struct {
	CommonDirVal   string
	CommonDirErr   error
	CurrentVal     string
	CurrentErr     error
	MainVal        string
	MainErr        error
	BranchVal      string
	BranchErr      error
	CommonDirCalls int
	CurrentCalls   int
	MainCalls      int
	BranchCalls    int
}

func (g *FakeGit) CommonDir(context.Context) (string, error) {
	g.CommonDirCalls++
	return g.CommonDirVal, g.CommonDirErr
}

func (g *FakeGit) CurrentWorktree(context.Context) (string, error) {
	g.CurrentCalls++
	return g.CurrentVal, g.CurrentErr
}

func (g *FakeGit) MainWorktree(context.Context) (string, error) {
	g.MainCalls++
	return g.MainVal, g.MainErr
}

func (g *FakeGit) Branch(context.Context) (string, error) {
	g.BranchCalls++
	return g.BranchVal, g.BranchErr
}

// ---------------------------------------------------------------------------
// MapEnv — env vars from a map.
// ---------------------------------------------------------------------------

type MapEnv struct {
	Vars map[string]string
}

func (e MapEnv) Get(name string) string { return e.Vars[name] }
func (e MapEnv) Lookup(name string) (string, bool) {
	v, ok := e.Vars[name]
	return v, ok
}

// ---------------------------------------------------------------------------
// FakePrompter — scripted responses.
// ---------------------------------------------------------------------------

// FakePrompter pops answers FIFO. Missing answers default to false/error/Unknown.
// Decisions is indexed alongside Conflict calls.
type FakePrompter struct {
	mu         sync.Mutex
	Confirms   []bool
	ConfirmErr []error
	Inputs     []string
	InputErr   []error
	Decisions  []di.Decision
	Calls      []string
}

func (p *FakePrompter) Confirm(msg string, _ bool) (bool, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.Calls = append(p.Calls, "confirm:"+msg)
	if len(p.Confirms) == 0 {
		return false, fmt.Errorf("FakePrompter: no scripted confirm")
	}
	v := p.Confirms[0]
	p.Confirms = p.Confirms[1:]
	var err error
	if len(p.ConfirmErr) > 0 {
		err = p.ConfirmErr[0]
		p.ConfirmErr = p.ConfirmErr[1:]
	}
	return v, err
}

func (p *FakePrompter) Input(msg, _, _ string) (string, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.Calls = append(p.Calls, "input:"+msg)
	if len(p.Inputs) == 0 {
		return "", fmt.Errorf("FakePrompter: no scripted input")
	}
	v := p.Inputs[0]
	p.Inputs = p.Inputs[1:]
	var err error
	if len(p.InputErr) > 0 {
		err = p.InputErr[0]
		p.InputErr = p.InputErr[1:]
	}
	return v, err
}

func (p *FakePrompter) Conflict(path string, _ func() (string, error)) (di.Decision, error) {
	p.mu.Lock()
	defer p.mu.Unlock()
	p.Calls = append(p.Calls, "conflict:"+path)
	if len(p.Decisions) == 0 {
		return di.DecisionUnknown, fmt.Errorf("FakePrompter: no scripted decision for %s", path)
	}
	d := p.Decisions[0]
	p.Decisions = p.Decisions[1:]
	return d, nil
}

// ---------------------------------------------------------------------------
// FakeClock, FakeTTY.
// ---------------------------------------------------------------------------

type FakeClock struct{ T time.Time }

func (c FakeClock) Now() time.Time { return c.T }

type FakeTTY struct{ Interactive bool }

func (t FakeTTY) IsInteractive() bool { return t.Interactive }

// ---------------------------------------------------------------------------
// BufferDeps is a convenience: a bundle of the most-used fakes with captured
// stdout/stderr buffers. Tests assemble a full di.Deps from these fields when
// calling code that takes di.Deps directly.
// ---------------------------------------------------------------------------

type BufferDeps struct {
	FS       *FakeFS
	Shell    *RecordShell
	Git      *FakeGit
	Env      MapEnv
	Prompter *FakePrompter
	TTY      FakeTTY
	Clock    FakeClock
	Stdout   *bytes.Buffer
	Stderr   *bytes.Buffer
}

func NewBufferDeps() BufferDeps {
	return BufferDeps{
		FS:       NewFakeFS(),
		Shell:    &RecordShell{},
		Git:      &FakeGit{},
		Env:      MapEnv{Vars: map[string]string{}},
		Prompter: &FakePrompter{},
		TTY:      FakeTTY{Interactive: true},
		Clock:    FakeClock{T: time.Date(2026, 7, 4, 12, 0, 0, 0, time.UTC)},
		Stdout:   &bytes.Buffer{},
		Stderr:   &bytes.Buffer{},
	}
}
